---
- name: Add recent Postgresql server apt key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: Add recent Pogstresql server repo
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main"
    state: present

- name: Install database deps
  apt: pkg={{ item }}
  with_items:
    - postgresql-{{ pg_version }}
    - postgresql-client-{{ pg_version }}
    - postgresql-contrib-{{ pg_version }}
    - libpq-dev
    - python-psycopg2
    - postgresql-{{ pg_version}}-postgis-{{ postgis_version }}

- name: Create db user
  postgresql_user:
    name: "{{ db_name }}"
    password: "{{ db_password }}"
    state: present
  become_user: postgres

- name: Create database
  postgresql_db:
    name: "{{ db_name }}"
    encoding: "UTF-8"
  become_user: postgres

- name: Enable db privileges
  postgresql_privs:
    database: "{{ db_name }}"
    role: "{{ db_name }}"
    privs: ALL
    objs: ALL_IN_SCHEMA
  become_user: postgres

- name: Enable postgis extension
  postgresql_ext:
    db: "{{ db_name }}"
    name: postgis
  become_user: postgres
